#list.append()
print("List Append Method")
list=[1,6,4,3,2,2,7,8,9,3,5,10]
print(list)
list.append(12)
list.append(13)
print(list)
print("--------------------------------------------------")

#list.insert()
print("List Insert Method")
print(list)
list.insert(2,100)
print(list)
list.insert(3,200)
print(list)
print("--------------------------------------------------")

#list.sort()
print("Printing Sort function")
print(list)
print(list.sort())
print(list)
print(list.sort(reverse=True))
print(list)
print("--------------------------------------------------")

#list.count()
print("Printing Count function")
print(list)
print(list.count(2))
print(list.count(10))
print("--------------------------------------------------")

#list.reverse()
print("Printing Reverse function")
print(list)
print(list.reverse())
print("--------------------------------------------------")

#list.copy()
print("Printing Copy function")
print(list)
print(list.copy())
print("--------------------------------------------------")
#list.extend()
print("Printing Extend function")
list1=[1,2,3,4,5,6,7,8,9]
list.extend(list1)
print(list)
print("--------------------------------------------------")
#list.index()
print("Printing Index function")
print(list)
print(list.index(2))
print("--------------------------------------------------")

#list.pop()
print("Printing Pop function")
print(list)
print(list.pop())
print(list.pop(2))
print("--------------------------------------------------")


#list.insert()
print("Printing Insert function")
print(list)
list.insert(2,100)
print(list)
list.insert(3,200)
print(list)
print("--------------------------------------------------")



#list.remove()
print("Printing Remove function")
print(list)
list.remove(100)
print(list)
list.remove(200)
print(list)
print("--------------------------------------------------")

#list.extend()
print("Printing Extend function")
list1=[1,2,3,4,5,6,7,8,9]
list.extend(list1)
print(list)
print("--------------------------------------------------")

#list.clear()
print("Printing Clear function")
print(list)
list.clear()
print(list)
print("--------------------------------------------------")
